import { z } from "zod";
export type { TemperaturePreference } from "@/lib/coffee-preferences";

const ingredientSchema = z.object({
  amount: z.string(),
  item: z.string(),
  note: z.string().optional(),
});

const coffeeSchema = z.object({
  slug: z.string(),
  name: z.string(),
  type: z.enum(["Black coffee", "Milk coffee", "Cold coffee", "Dessert coffee", "Tea latte"]),
  origin: z.string(),
  served: z.enum(["Hot", "Iced", "Cold", "Hot & cold"]),
  withMilk: z.boolean(),
  strength: z.number().min(1).max(5),
  sweetness: z.number().min(1).max(5),
  description: z.string(),
  character: z.string(),
  recipeTitle: z.string(),
  ingredients: z.array(ingredientSchema),
  steps: z.array(z.string()),
  visual: z.enum(["espresso", "black", "milk", "iced", "cold", "green", "dessert"]),
  tone: z.string(),
});

export type Coffee = z.infer<typeof coffeeSchema>;
export type CoffeeBrowserItem = Pick<Coffee, "description" | "name" | "origin" | "served" | "slug" | "tone" | "type" | "visual" | "withMilk">;
export type CoffeeDiscoveryItem = Pick<Coffee, "character" | "name" | "origin" | "served" | "slug" | "strength" | "sweetness" | "type" | "withMilk">;
const coffeeData: Coffee[] = [
  {
    slug: "espresso",
    name: "Espresso",
    type: "Black coffee",
    origin: "Italy",
    served: "Hot",
    withMilk: false,
    strength: 5,
    sweetness: 1,
    description: "A small, concentrated coffee with a rich crema and a long finish.",
    character: "Short, intense, and aromatic.",
    recipeTitle: "Classic espresso",
    ingredients: [{ amount: "18 g", item: "Finely ground coffee" }],
    steps: ["Warm the cup and flush the group head.", "Dose, distribute, and tamp the coffee evenly.", "Pull roughly 36 g of espresso in about 25 to 30 seconds."],
    visual: "espresso",
    tone: "#8b4f2d",
  },
  {
    slug: "americano",
    name: "Americano",
    type: "Black coffee",
    origin: "Italian-American café tradition",
    served: "Hot",
    withMilk: false,
    strength: 3,
    sweetness: 1,
    description: "Espresso diluted with hot water for a longer, lighter cup.",
    character: "Long, clear, and quietly bold.",
    recipeTitle: "Everyday Americano",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "120 ml", item: "Hot water" }],
    steps: ["Pull a double espresso into a warmed cup.", "Add the hot water to dilute it to taste.", "Stir gently and serve immediately."],
    visual: "black",
    tone: "#57301f",
  },
  {
    slug: "cappuccino",
    name: "Cappuccino",
    type: "Milk coffee",
    origin: "Italy",
    served: "Hot",
    withMilk: true,
    strength: 3,
    sweetness: 2,
    description: "Espresso balanced with steam-foamed milk in a compact cup with a generous velvety cap.",
    character: "Foamy, balanced, and comforting.",
    recipeTitle: "Traditional cappuccino",
    ingredients: [{ amount: "25 ml", item: "Espresso", note: "1 shot" }, { amount: "100 ml", item: "Cold whole milk", note: "steam-foamed" }],
    steps: ["Pull a 25 ml espresso into a warmed cappuccino cup.", "Steam the milk into glossy foam without separating it into dry layers.", "Pour the textured milk through the espresso, finishing with a generous foam cap."],
    visual: "milk",
    tone: "#b8733f",
  },
  {
    slug: "flat-white",
    name: "Flat White",
    type: "Milk coffee",
    origin: "Australia & New Zealand",
    served: "Hot",
    withMilk: true,
    strength: 4,
    sweetness: 2,
    description: "A double espresso softened with a thin layer of silky microfoam.",
    character: "Velvety, compact, and coffee-forward.",
    recipeTitle: "Silky flat white",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "120 ml", item: "Steamed milk" }],
    steps: ["Pull a double espresso into a small cup.", "Steam milk to a glossy, paint-like texture.", "Pour low and steadily, keeping the foam layer thin."],
    visual: "milk",
    tone: "#c18451",
  },
  {
    slug: "cortado",
    name: "Cortado",
    type: "Milk coffee",
    origin: "Spain",
    served: "Hot",
    withMilk: true,
    strength: 4,
    sweetness: 2,
    description: "Espresso cut with an equal amount of warm milk to soften its edge.",
    character: "Small, smooth, and direct.",
    recipeTitle: "Balanced cortado",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "36 ml", item: "Warm textured milk" }],
    steps: ["Pull a double espresso into a small glass.", "Texture a little milk with minimal foam.", "Pour equal parts milk and espresso."],
    visual: "milk",
    tone: "#aa693f",
  },
  {
    slug: "latte",
    name: "Latte",
    type: "Milk coffee",
    origin: "Italy",
    served: "Hot",
    withMilk: true,
    strength: 2,
    sweetness: 3,
    description: "Espresso with plenty of steamed milk and a delicate cap of microfoam.",
    character: "Gentle, creamy, and adaptable.",
    recipeTitle: "Classic café latte",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "180 ml", item: "Steamed milk" }],
    steps: ["Pull a double espresso into a large cup.", "Steam milk until silky with a fine microfoam.", "Pour slowly, folding the milk through the espresso."],
    visual: "milk",
    tone: "#d19a68",
  },
  {
    slug: "iced-latte",
    name: "Iced Latte",
    type: "Cold coffee",
    origin: "Modern global café culture",
    served: "Iced",
    withMilk: true,
    strength: 2,
    sweetness: 3,
    description: "Chilled milk, ice, and espresso layered into a cool, creamy drink.",
    character: "Cool, creamy, and refreshing.",
    recipeTitle: "Everyday iced latte",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "150 ml", item: "Cold milk" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Fill a tall glass generously with ice.", "Pour in the cold milk.", "Add freshly pulled espresso and stir before drinking."],
    visual: "iced",
    tone: "#c88a55",
  },
  {
    slug: "cold-brew",
    name: "Cold Brew",
    type: "Cold coffee",
    origin: "Modern global café culture",
    served: "Iced",
    withMilk: false,
    strength: 3,
    sweetness: 2,
    description: "Coffee steeped in cold water for a smooth, mellow cup with gentle perceived acidity.",
    character: "Round, mellow, and deeply refreshing.",
    recipeTitle: "Ready-to-drink cold brew",
    ingredients: [{ amount: "60 g", item: "Coarsely ground coffee" }, { amount: "1 litre", item: "Cold filtered water" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Combine coffee and water in a covered jug.", "Steep in the refrigerator for 12 to 16 hours.", "Strain through a fine filter and serve over ice."],
    visual: "iced",
    tone: "#4f2c21",
  },
  {
    slug: "espresso-tonic",
    name: "Espresso Tonic",
    type: "Cold coffee",
    origin: "Sweden",
    served: "Iced",
    withMilk: false,
    strength: 3,
    sweetness: 3,
    description: "Bright tonic water and espresso meet in a sparkling, bittersweet highball.",
    character: "Fizzy, bright, and unexpectedly elegant.",
    recipeTitle: "Sparkling espresso tonic",
    ingredients: [{ amount: "120 ml", item: "Chilled tonic water" }, { amount: "36 ml", item: "Double espresso" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Fill a tall glass with clear ice.", "Add tonic water slowly to preserve the bubbles.", "Float a freshly pulled espresso over the top."],
    visual: "iced",
    tone: "#805337",
  },
  {
    slug: "mocha",
    name: "Mocha",
    type: "Dessert coffee",
    origin: "Modern café culture",
    served: "Hot",
    withMilk: true,
    strength: 3,
    sweetness: 5,
    description: "Espresso, chocolate, and steamed milk in a rich café classic.",
    character: "Chocolatey, plush, and generous.",
    recipeTitle: "Dark chocolate mocha",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "20 g", item: "Dark chocolate" }, { amount: "150 ml", item: "Steamed milk" }],
    steps: ["Melt the chocolate into the hot espresso.", "Steam the milk until smooth and glossy.", "Pour into the chocolate espresso and finish with a thin cap of foam."],
    visual: "dessert",
    tone: "#70402b",
  },
  {
    slug: "affogato",
    name: "Affogato",
    type: "Dessert coffee",
    origin: "Italy",
    served: "Hot & cold",
    withMilk: true,
    strength: 4,
    sweetness: 5,
    description: "A hot espresso poured over cold vanilla gelato just before serving.",
    character: "Hot, cold, bitter, sweet.",
    recipeTitle: "Simple affogato",
    ingredients: [{ amount: "1 scoop", item: "Vanilla gelato" }, { amount: "30 ml", item: "Fresh espresso" }],
    steps: ["Place a firm scoop of gelato in a chilled glass.", "Pull a fresh espresso.", "Pour it over the gelato at the table and eat immediately."],
    visual: "dessert",
    tone: "#b06e3d",
  },
  {
    slug: "matcha-latte",
    name: "Matcha Latte",
    type: "Tea latte",
    origin: "Japan-inspired café drink",
    served: "Hot",
    withMilk: true,
    strength: 2,
    sweetness: 3,
    description: "Stone-ground green tea whisked smooth and finished with steamed milk.",
    character: "Grassy, creamy, and calm.",
    recipeTitle: "Whisked matcha latte",
    ingredients: [{ amount: "2 g", item: "Ceremonial matcha" }, { amount: "40 ml", item: "Hot water" }, { amount: "160 ml", item: "Steamed milk" }],
    steps: ["Sift matcha into a wide bowl.", "Add hot—not boiling—water and whisk until frothy.", "Pour in silky steamed milk and serve."],
    visual: "green",
    tone: "#778b4a",
  },
  {
    slug: "caramel-macchiato",
    name: "Caramel Macchiato",
    type: "Dessert coffee",
    origin: "United States",
    served: "Iced",
    withMilk: true,
    strength: 2,
    sweetness: 5,
    description: "Vanilla-sweetened milk and espresso layered over ice, finished with caramel drizzle.",
    character: "Sweet, layered, and indulgent.",
    recipeTitle: "Iced caramel macchiato",
    ingredients: [{ amount: "15 ml", item: "Vanilla syrup" }, { amount: "150 ml", item: "Cold milk" }, { amount: "36 ml", item: "Double espresso" }, { amount: "1 cup", item: "Ice" }, { amount: "10 ml", item: "Caramel sauce", note: "for drizzling" }],
    steps: ["Stir the vanilla syrup into the milk and pour it over ice.", "Float the fresh espresso over the milk.", "Finish with caramel sauce across the top."],
    visual: "iced",
    tone: "#d09357",
  },
  {
    slug: "turkish-coffee",
    name: "Turkish Coffee",
    type: "Black coffee",
    origin: "Türkiye",
    served: "Hot",
    withMilk: false,
    strength: 5,
    sweetness: 2,
    description: "Finely ground coffee brewed unfiltered in a cezve until richly foamed.",
    character: "Dense, fragrant, and ceremonial.",
    recipeTitle: "Traditional Turkish coffee",
    ingredients: [{ amount: "7 g", item: "Powder-fine coffee" }, { amount: "70 ml", item: "Cold water" }, { amount: "Optional", item: "Sugar" }],
    steps: ["Combine coffee, water, and optional sugar in a cezve.", "Heat slowly without stirring until a cap of foam rises.", "Pour gently into a small cup and allow the grounds to settle."],
    visual: "black",
    tone: "#4b2a1f",
  },
  {
    slug: "doppio",
    name: "Doppio",
    type: "Black coffee",
    origin: "Italy",
    served: "Hot",
    withMilk: false,
    strength: 5,
    sweetness: 1,
    description: "A double portion of espresso with the same concentrated character and a generous cap of crema.",
    character: "Compact, intense, and aromatic.",
    recipeTitle: "Classic doppio",
    ingredients: [{ amount: "18 g", item: "Finely ground coffee" }],
    steps: ["Dose and evenly tamp the coffee in a double basket.", "Pull roughly 36 g of espresso in about 25 to 30 seconds.", "Serve immediately in a warmed cup."],
    visual: "espresso",
    tone: "#6f412b",
  },
  {
    slug: "ristretto",
    name: "Ristretto",
    type: "Black coffee",
    origin: "Italy",
    served: "Hot",
    withMilk: false,
    strength: 5,
    sweetness: 2,
    description: "A short espresso extraction that highlights syrupy texture and concentrated sweetness.",
    character: "Syrupy, vivid, and fleeting.",
    recipeTitle: "Short ristretto",
    ingredients: [{ amount: "18 g", item: "Finely ground coffee" }],
    steps: ["Dose and tamp the coffee evenly.", "Pull a short 20 to 25 g extraction in roughly 20 seconds.", "Serve at once in a demitasse."],
    visual: "espresso",
    tone: "#75412a",
  },
  {
    slug: "lungo",
    name: "Lungo",
    type: "Black coffee",
    origin: "Italy",
    served: "Hot",
    withMilk: false,
    strength: 4,
    sweetness: 1,
    description: "An espresso pulled longer for a larger, more bittersweet cup.",
    character: "Long, roasty, and lingering.",
    recipeTitle: "Espresso lungo",
    ingredients: [{ amount: "18 g", item: "Finely ground coffee" }],
    steps: ["Dose and tamp the coffee in the portafilter.", "Pull a 50 to 60 g shot over about 35 to 40 seconds.", "Serve without delay."],
    visual: "espresso",
    tone: "#79503a",
  },
  {
    slug: "long-black",
    name: "Long Black",
    type: "Black coffee",
    origin: "Australia and New Zealand",
    served: "Hot",
    withMilk: false,
    strength: 4,
    sweetness: 1,
    description: "Double espresso poured over hot water to preserve its fragrant crema.",
    character: "Bold, clean, and crema-topped.",
    recipeTitle: "Long black",
    ingredients: [{ amount: "100 ml", item: "Hot water" }, { amount: "36 ml", item: "Double espresso" }],
    steps: ["Add hot water to a preheated cup.", "Pull a fresh double espresso.", "Pour the espresso gently over the water to keep the crema intact."],
    visual: "black",
    tone: "#49362d",
  },
  {
    slug: "red-eye",
    name: "Red Eye",
    type: "Black coffee",
    origin: "United States",
    served: "Hot",
    withMilk: false,
    strength: 5,
    sweetness: 1,
    description: "Fresh brewed coffee reinforced with a shot of espresso for serious momentum.",
    character: "Direct, energizing, and full-bodied.",
    recipeTitle: "Red eye coffee",
    ingredients: [{ amount: "240 ml", item: "Fresh brewed coffee" }, { amount: "30 ml", item: "Espresso" }],
    steps: ["Brew a full cup of coffee.", "Pull a fresh espresso shot.", "Pour the espresso into the brewed coffee and serve hot."],
    visual: "black",
    tone: "#382821",
  },
  {
    slug: "cafe-cubano",
    name: "Café Cubano",
    type: "Black coffee",
    origin: "Cuba",
    served: "Hot",
    withMilk: false,
    strength: 5,
    sweetness: 5,
    description: "Strong moka-pot coffee sweetened with a whipped sugar foam called espuma.",
    character: "Potent, sweet, and celebratory.",
    recipeTitle: "Cuban coffee",
    ingredients: [{ amount: "18 g", item: "Fine dark-roast coffee" }, { amount: "20 g", item: "Granulated sugar" }, { amount: "60 ml", item: "Water" }],
    steps: ["Begin brewing the coffee in a moka pot.", "Whip the first few drops with sugar until pale and foamy.", "Stir in the remaining coffee and spoon the espuma on top."],
    visual: "espresso",
    tone: "#a96332",
  },
  {
    slug: "cafe-de-olla",
    name: "Café de Olla",
    type: "Black coffee",
    origin: "Mexico",
    served: "Hot",
    withMilk: false,
    strength: 3,
    sweetness: 4,
    description: "Coffee simmered with cinnamon and piloncillo for a warmly spiced cup.",
    character: "Rustic, spiced, and comforting.",
    recipeTitle: "Cinnamon café de olla",
    ingredients: [{ amount: "25 g", item: "Coarsely ground coffee" }, { amount: "500 ml", item: "Water" }, { amount: "35 g", item: "Piloncillo or dark brown sugar" }, { amount: "1 stick", item: "Cinnamon" }],
    steps: ["Simmer the water, piloncillo, and cinnamon until dissolved.", "Add the coffee, remove from heat, and steep for 5 minutes.", "Strain into clay mugs or heatproof cups."],
    visual: "black",
    tone: "#a04f2f",
  },
  {
    slug: "moka-pot",
    name: "Moka Pot",
    type: "Black coffee",
    origin: "Italy",
    served: "Hot",
    withMilk: false,
    strength: 4,
    sweetness: 1,
    description: "Stovetop coffee with an espresso-like body and unmistakably roasty aroma.",
    character: "Robust, familiar, and concentrated.",
    recipeTitle: "Stovetop moka coffee",
    ingredients: [{ amount: "18 g", item: "Medium-fine coffee" }, { amount: "180 ml", item: "Hot water" }],
    steps: ["Fill the lower chamber to just below the valve and loosely level coffee in the basket.", "Assemble and heat over medium-low with the lid open.", "Remove when the stream turns pale, then stir and pour."],
    visual: "black",
    tone: "#524239",
  },
  {
    slug: "pour-over",
    name: "Pour Over",
    type: "Black coffee",
    origin: "Modern filter-coffee tradition",
    served: "Hot",
    withMilk: false,
    strength: 3,
    sweetness: 2,
    description: "Hand-filtered coffee that brings clarity and delicate aromas to the foreground.",
    character: "Clean, nuanced, and contemplative.",
    recipeTitle: "Balanced pour over",
    ingredients: [{ amount: "20 g", item: "Medium-ground coffee" }, { amount: "320 g", item: "Water at 93°C" }, { amount: "1", item: "Paper filter" }],
    steps: ["Rinse the filter, add coffee, and level the bed.", "Bloom with 50 g of water for 40 seconds.", "Pour the remaining water slowly in circles, finishing near 3 minutes."],
    visual: "black",
    tone: "#8a6247",
  },
  {
    slug: "french-press",
    name: "French Press",
    type: "Black coffee",
    origin: "France and Italy",
    served: "Hot",
    withMilk: false,
    strength: 3,
    sweetness: 2,
    description: "Full-immersion coffee with a rounded body and aromatic oils left intact.",
    character: "Round, rich, and unhurried.",
    recipeTitle: "Four-minute French press",
    ingredients: [{ amount: "30 g", item: "Coarsely ground coffee" }, { amount: "500 g", item: "Water at 94°C" }],
    steps: ["Add coffee to the press and saturate it with all the water.", "Stir gently and steep for 4 minutes.", "Press slowly and decant immediately."],
    visual: "black",
    tone: "#675142",
  },
  {
    slug: "aeropress",
    name: "AeroPress",
    type: "Black coffee",
    origin: "United States",
    served: "Hot",
    withMilk: false,
    strength: 3,
    sweetness: 2,
    description: "A compact pressure brew with a clean cup, gentle body, and quick finish.",
    character: "Bright, tidy, and adaptable.",
    recipeTitle: "Everyday AeroPress",
    ingredients: [{ amount: "16 g", item: "Medium-fine coffee" }, { amount: "230 g", item: "Water at 90°C" }, { amount: "1", item: "Paper filter" }],
    steps: ["Rinse the filter and add the coffee to the chamber.", "Pour in the water, stir, and steep for 90 seconds.", "Press gently for about 30 seconds."],
    visual: "black",
    tone: "#78604e",
  },
  {
    slug: "cafe-au-lait",
    name: "Café au Lait",
    type: "Milk coffee",
    origin: "France",
    served: "Hot",
    withMilk: true,
    strength: 2,
    sweetness: 2,
    description: "Strong brewed coffee and hot milk in equal measure, traditionally served in a bowl.",
    character: "Soft, generous, and breakfast-ready.",
    recipeTitle: "French café au lait",
    ingredients: [{ amount: "150 ml", item: "Strong brewed coffee" }, { amount: "150 ml", item: "Hot milk" }],
    steps: ["Brew the coffee slightly stronger than usual.", "Heat the milk until steaming without creating much foam.", "Pour coffee and milk together into a wide cup."],
    visual: "milk",
    tone: "#c8a27d",
  },
  {
    slug: "cafe-con-leche",
    name: "Café con Leche",
    type: "Milk coffee",
    origin: "Spain",
    served: "Hot",
    withMilk: true,
    strength: 3,
    sweetness: 2,
    description: "Dark espresso mellowed by nearly equal parts hot, lightly textured milk.",
    character: "Bold, milky, and morning-friendly.",
    recipeTitle: "Spanish café con leche",
    ingredients: [{ amount: "60 ml", item: "Strong espresso" }, { amount: "90 ml", item: "Hot milk" }, { amount: "Optional", item: "Sugar" }],
    steps: ["Pull the espresso into a sturdy glass.", "Heat the milk until very hot with only a little foam.", "Combine, sweeten if desired, and serve."],
    visual: "milk",
    tone: "#ba8c64",
  },
  {
    slug: "spanish-latte",
    name: "Spanish Latte",
    type: "Dessert coffee",
    origin: "Modern café culture",
    served: "Hot",
    withMilk: true,
    strength: 2,
    sweetness: 5,
    description: "Espresso, silky milk, and condensed milk in a lush café-style drink.",
    character: "Velvety, sweet, and generous.",
    recipeTitle: "Hot Spanish latte",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "25 ml", item: "Sweetened condensed milk" }, { amount: "140 ml", item: "Steamed milk" }],
    steps: ["Stir the condensed milk into the fresh espresso.", "Steam the milk to a silky microfoam.", "Pour the milk over the sweetened espresso."],
    visual: "milk",
    tone: "#d0a070",
  },
  {
    slug: "piccolo-latte",
    name: "Piccolo Latte",
    type: "Milk coffee",
    origin: "Australia",
    served: "Hot",
    withMilk: true,
    strength: 4,
    sweetness: 2,
    description: "A ristretto softened with a small amount of textured milk in a tiny glass.",
    character: "Small, silky, and coffee-forward.",
    recipeTitle: "Piccolo latte",
    ingredients: [{ amount: "30 ml", item: "Ristretto" }, { amount: "60 ml", item: "Steamed milk" }],
    steps: ["Pull a ristretto into a 90 ml glass.", "Steam the milk to fine, glossy microfoam.", "Pour a thin layer of milk through the centre."],
    visual: "milk",
    tone: "#ae805f",
  },
  {
    slug: "espresso-macchiato",
    name: "Espresso Macchiato",
    type: "Milk coffee",
    origin: "Italy",
    served: "Hot",
    withMilk: true,
    strength: 5,
    sweetness: 1,
    description: "Espresso marked with just a spoonful of milk foam.",
    character: "Punchy, foamy, and precise.",
    recipeTitle: "Traditional macchiato",
    ingredients: [{ amount: "30 ml", item: "Espresso" }, { amount: "15 ml", item: "Milk foam" }],
    steps: ["Pull a fresh espresso into a demitasse.", "Steam a small amount of milk until glossy.", "Mark the espresso with a spoonful of foam."],
    visual: "espresso",
    tone: "#956546",
  },
  {
    slug: "latte-macchiato",
    name: "Latte Macchiato",
    type: "Milk coffee",
    origin: "Italy",
    served: "Hot",
    withMilk: true,
    strength: 2,
    sweetness: 2,
    description: "Steamed milk marked by espresso, creating distinct layers in a tall glass.",
    character: "Layered, gentle, and elegant.",
    recipeTitle: "Layered latte macchiato",
    ingredients: [{ amount: "180 ml", item: "Steamed milk" }, { amount: "30 ml", item: "Espresso" }],
    steps: ["Steam milk with a generous cap of fine foam.", "Pour the milk into a tall glass and rest for 20 seconds.", "Slowly add espresso through the foam to form layers."],
    visual: "milk",
    tone: "#d2b08e",
  },
  {
    slug: "cafe-breve",
    name: "Café Breve",
    type: "Dessert coffee",
    origin: "United States",
    served: "Hot",
    withMilk: true,
    strength: 3,
    sweetness: 3,
    description: "Espresso finished with steamed half-and-half for an extra-rich texture.",
    character: "Plush, creamy, and decadent.",
    recipeTitle: "American café breve",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "140 ml", item: "Half-and-half" }],
    steps: ["Pull a double espresso into a warm cup.", "Steam the half-and-half carefully to glossy foam.", "Pour it into the espresso and finish with a thin foam cap."],
    visual: "dessert",
    tone: "#d5a879",
  },
  {
    slug: "vietnamese-iced-coffee",
    name: "Vietnamese Iced Coffee",
    type: "Cold coffee",
    origin: "Vietnam",
    served: "Iced",
    withMilk: true,
    strength: 5,
    sweetness: 5,
    description: "Slow-dripped dark coffee stirred with condensed milk and poured over ice.",
    character: "Intense, sweet, and slowly unfolding.",
    recipeTitle: "Cà phê sữa đá",
    ingredients: [{ amount: "20 g", item: "Medium-fine dark-roast coffee" }, { amount: "30 ml", item: "Sweetened condensed milk" }, { amount: "90 ml", item: "Hot water" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Add condensed milk to a glass and set a phin filter on top.", "Bloom the coffee, add the remaining water, and let it drip slowly.", "Stir thoroughly and pour over a fresh glass of ice."],
    visual: "iced",
    tone: "#b76635",
  },
  {
    slug: "iced-americano",
    name: "Iced Americano",
    type: "Cold coffee",
    origin: "United States",
    served: "Iced",
    withMilk: false,
    strength: 4,
    sweetness: 1,
    description: "Espresso lengthened with cold water and plenty of ice for a crisp finish.",
    character: "Brisk, bold, and refreshing.",
    recipeTitle: "Crisp iced Americano",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "120 ml", item: "Cold water" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Fill a tall glass with ice and cold water.", "Pull a fresh double espresso.", "Pour the espresso over the top and stir once."],
    visual: "iced",
    tone: "#4e3a31",
  },
  {
    slug: "iced-mocha",
    name: "Iced Mocha",
    type: "Dessert coffee",
    origin: "United States",
    served: "Iced",
    withMilk: true,
    strength: 3,
    sweetness: 4,
    description: "Chilled espresso and milk with dark chocolate folded through every sip.",
    character: "Chocolatey, cool, and satisfying.",
    recipeTitle: "Iced café mocha",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "20 g", item: "Dark chocolate sauce" }, { amount: "150 ml", item: "Cold milk" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Stir the chocolate into the hot espresso until smooth.", "Fill a glass with ice and cold milk.", "Pour in the chocolate espresso and stir."],
    visual: "iced",
    tone: "#704838",
  },
  {
    slug: "iced-spanish-latte",
    name: "Iced Spanish Latte",
    type: "Dessert coffee",
    origin: "Modern café culture",
    served: "Iced",
    withMilk: true,
    strength: 2,
    sweetness: 5,
    description: "Condensed milk, fresh espresso, and cold milk layered over ice.",
    character: "Lush, chilled, and crowd-pleasing.",
    recipeTitle: "Iced Spanish latte",
    ingredients: [{ amount: "30 ml", item: "Sweetened condensed milk" }, { amount: "140 ml", item: "Cold milk" }, { amount: "36 ml", item: "Double espresso" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Stir the condensed milk with the cold milk.", "Fill a tall glass with ice and add the milk mixture.", "Float the fresh espresso over the top and stir before drinking."],
    visual: "iced",
    tone: "#d4a16e",
  },
  {
    slug: "dalgona-coffee",
    name: "Dalgona Coffee",
    type: "Dessert coffee",
    origin: "Popularised in South Korea",
    served: "Iced",
    withMilk: true,
    strength: 2,
    sweetness: 5,
    description: "A cloud of whipped coffee spooned over cold milk and ice.",
    character: "Fluffy, playful, and sweet.",
    recipeTitle: "Whipped dalgona coffee",
    ingredients: [{ amount: "12 g", item: "Instant coffee" }, { amount: "12 g", item: "Sugar" }, { amount: "15 ml", item: "Hot water" }, { amount: "180 ml", item: "Cold milk" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Whip the instant coffee, sugar, and hot water until thick and glossy.", "Fill a glass with ice and cold milk.", "Spoon the coffee foam over the milk and stir before drinking."],
    visual: "dessert",
    tone: "#c78d58",
  },
  {
    slug: "shakerato",
    name: "Shakerato",
    type: "Cold coffee",
    origin: "Italy",
    served: "Iced",
    withMilk: false,
    strength: 4,
    sweetness: 2,
    description: "Espresso shaken hard with ice into a cold, satin-textured foam.",
    character: "Sleek, brisk, and theatrical.",
    recipeTitle: "Italian caffè shakerato",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "10 ml", item: "Simple syrup", note: "Optional" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Add fresh espresso, ice, and optional syrup to a cocktail shaker.", "Shake vigorously for 15 seconds.", "Double-strain into a chilled glass to keep the fine foam."],
    visual: "iced",
    tone: "#76513e",
  },
  {
    slug: "freddo-espresso",
    name: "Freddo Espresso",
    type: "Cold coffee",
    origin: "Greece",
    served: "Iced",
    withMilk: false,
    strength: 5,
    sweetness: 1,
    description: "Double espresso chilled and aerated over ice for a foamy Greek favourite.",
    character: "Powerful, cold, and lively.",
    recipeTitle: "Greek freddo espresso",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "1 cup", item: "Ice" }, { amount: "Optional", item: "Sugar" }],
    steps: ["Pull a double espresso and dissolve in sugar if desired.", "Blend or shake it briefly with a few ice cubes until foamy.", "Strain over fresh ice in a tall glass."],
    visual: "iced",
    tone: "#68432f",
  },
  {
    slug: "freddo-cappuccino",
    name: "Freddo Cappuccino",
    type: "Cold coffee",
    origin: "Greece",
    served: "Iced",
    withMilk: true,
    strength: 4,
    sweetness: 2,
    description: "Iced foamy espresso crowned with a layer of velvety cold milk foam.",
    character: "Airy, cool, and coffee-forward.",
    recipeTitle: "Greek freddo cappuccino",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "60 ml", item: "Cold low-fat milk" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Shake or blend the espresso with a few ice cubes until foamy.", "Froth the cold milk until thick and glossy.", "Pour espresso over fresh ice and spoon the cold foam on top."],
    visual: "iced",
    tone: "#a77856",
  },
  {
    slug: "nitro-cold-brew",
    name: "Nitro Cold Brew",
    type: "Cold coffee",
    origin: "United States",
    served: "Cold",
    withMilk: false,
    strength: 4,
    sweetness: 2,
    description: "Cold brew infused with nitrogen for a cascading head and creamy mouthfeel.",
    character: "Silky, dark, and draft-like.",
    recipeTitle: "Home nitro cold brew",
    ingredients: [{ amount: "250 ml", item: "Chilled ready-to-drink cold brew" }, { amount: "1", item: "Pure nitrogen charger", note: "compatible with the whipper" }],
    steps: ["Chill the prepared cold brew completely.", "Pour it into a compatible nitro whipper and charge according to its directions.", "Dispense firmly into a cold glass and let the cascade settle."],
    visual: "cold",
    tone: "#312b28",
  },
  {
    slug: "mazagran",
    name: "Mazagran",
    type: "Cold coffee",
    origin: "Portugal, with Algerian roots",
    served: "Iced",
    withMilk: false,
    strength: 3,
    sweetness: 3,
    description: "Portuguese-style chilled coffee brightened with lemon for a tart, refreshing summer drink.",
    character: "Citrusy, brisk, and surprising.",
    recipeTitle: "Portuguese lemon mazagran",
    ingredients: [{ amount: "150 ml", item: "Chilled strong coffee" }, { amount: "20 ml", item: "Fresh lemon juice" }, { amount: "10 ml", item: "Simple syrup" }, { amount: "1 cup", item: "Ice" }],
    steps: ["Stir the chilled coffee with lemon juice and syrup.", "Fill a tall glass with ice.", "Pour over the coffee mixture and garnish with lemon peel."],
    visual: "iced",
    tone: "#a56f3b",
  },
  {
    slug: "greek-frappe",
    name: "Greek Frappé",
    type: "Cold coffee",
    origin: "Greece",
    served: "Iced",
    withMilk: false,
    strength: 3,
    sweetness: 2,
    description: "Instant coffee shaken into a lasting foam, then stretched with cold water and ice.",
    character: "Foamy, nostalgic, and leisurely.",
    recipeTitle: "Classic Greek frappé",
    ingredients: [{ amount: "4 g", item: "Instant coffee" }, { amount: "30 ml", item: "Cold water" }, { amount: "120 ml", item: "Cold water" }, { amount: "1 cup", item: "Ice" }, { amount: "Optional", item: "Sugar or evaporated milk" }],
    steps: ["Shake the instant coffee, first measure of water, and optional sugar until very foamy.", "Pour into a tall glass over ice.", "Top with the remaining water and optional evaporated milk."],
    visual: "iced",
    tone: "#9c775c",
  },
  {
    slug: "cafe-bombon",
    name: "Café Bombón",
    type: "Dessert coffee",
    origin: "Spain",
    served: "Hot",
    withMilk: true,
    strength: 4,
    sweetness: 5,
    description: "Espresso layered over condensed milk in a small transparent glass.",
    character: "Tiny, dramatic, and very sweet.",
    recipeTitle: "Layered café bombón",
    ingredients: [{ amount: "30 ml", item: "Sweetened condensed milk" }, { amount: "30 ml", item: "Espresso" }],
    steps: ["Pour condensed milk into a heatproof glass.", "Pull a fresh espresso into a small pitcher.", "Pour the espresso slowly over a spoon to preserve the layers."],
    visual: "dessert",
    tone: "#cc8c50",
  },
  {
    slug: "irish-coffee",
    name: "Irish Coffee",
    type: "Dessert coffee",
    origin: "Ireland",
    served: "Hot",
    withMilk: true,
    strength: 3,
    sweetness: 3,
    description: "Hot coffee, Irish whiskey, and sugar beneath cool, lightly whipped cream.",
    character: "Warming, spirited, and luxurious.",
    recipeTitle: "Classic Irish coffee",
    ingredients: [{ amount: "120 ml", item: "Hot brewed coffee" }, { amount: "50 ml", item: "Irish whiskey" }, { amount: "1 tsp", item: "Sugar" }, { amount: "50 ml", item: "Chilled, lightly whipped cream" }],
    steps: ["Warm a heatproof glass and dissolve the sugar in hot coffee.", "Stir in the Irish whiskey.", "Float lightly whipped cream over the back of a spoon and sip through it."],
    visual: "dessert",
    tone: "#825239",
  },
  {
    slug: "vienna-coffee",
    name: "Einspänner",
    type: "Dessert coffee",
    origin: "Austria",
    served: "Hot",
    withMilk: true,
    strength: 4,
    sweetness: 2,
    description: "A Viennese double espresso protected by a generous cap of whipped cream in a handled glass.",
    character: "Grand, creamy, and old-world.",
    recipeTitle: "Traditional Viennese Einspänner",
    ingredients: [{ amount: "60 ml", item: "Double espresso" }, { amount: "50 ml", item: "Whipped cream" }, { amount: "Optional", item: "Powdered sugar" }],
    steps: ["Pull a double espresso into a clear handled glass.", "Sweeten lightly if desired.", "Spoon a thick layer of whipped cream over the surface."],
    visual: "dessert",
    tone: "#bea083",
  },
  {
    slug: "eiskaffee",
    name: "Eiskaffee",
    type: "Dessert coffee",
    origin: "Germany",
    served: "Iced",
    withMilk: true,
    strength: 2,
    sweetness: 5,
    description: "Chilled coffee poured over vanilla ice cream and finished with whipped cream.",
    character: "Retro, cooling, and unabashedly indulgent.",
    recipeTitle: "German eiskaffee",
    ingredients: [{ amount: "180 ml", item: "Chilled brewed coffee" }, { amount: "2 scoops", item: "Vanilla ice cream" }, { amount: "40 ml", item: "Whipped cream" }, { amount: "Optional", item: "Chocolate shavings" }],
    steps: ["Place the vanilla ice cream in a tall chilled glass.", "Pour the cold coffee around the scoops.", "Top with whipped cream and optional chocolate shavings."],
    visual: "dessert",
    tone: "#c99d72",
  },
  {
    slug: "marocchino",
    name: "Marocchino",
    type: "Dessert coffee",
    origin: "Italy",
    served: "Hot",
    withMilk: true,
    strength: 4,
    sweetness: 3,
    description: "Espresso, cocoa, and milk foam assembled in a small glass.",
    character: "Cocoa-dusted, compact, and refined.",
    recipeTitle: "Italian marocchino",
    ingredients: [{ amount: "30 ml", item: "Espresso" }, { amount: "5 g", item: "Unsweetened cocoa" }, { amount: "30 ml", item: "Milk foam" }],
    steps: ["Dust the base of a small glass with half the cocoa.", "Add the fresh espresso and spoon milk foam over it.", "Finish with the remaining cocoa."],
    visual: "dessert",
    tone: "#8d5d43",
  },
  {
    slug: "bicerin",
    name: "Bicerin",
    type: "Dessert coffee",
    origin: "Turin, Italy",
    served: "Hot",
    withMilk: true,
    strength: 3,
    sweetness: 5,
    description: "Distinct layers of drinking chocolate, coffee, and cold cream, traditionally enjoyed without stirring.",
    character: "Historic, luxurious, and bittersweet.",
    recipeTitle: "Turinese-style bicerin",
    ingredients: [{ amount: "60 ml", item: "Thick hot chocolate" }, { amount: "45 ml", item: "Strong brewed coffee" }, { amount: "30 ml", item: "Cold lightly whipped cream" }],
    steps: ["Pour thick hot chocolate into a heatproof glass.", "Float the coffee gently over the chocolate.", "Finish with a cool layer of lightly whipped cream and serve without stirring."],
    visual: "dessert",
    tone: "#6f4232",
  },
  {
    slug: "cafe-miel",
    name: "Café Miel",
    type: "Dessert coffee",
    origin: "Modern café culture",
    served: "Hot",
    withMilk: true,
    strength: 3,
    sweetness: 4,
    description: "Espresso and steamed milk sweetened with honey and warmed with cinnamon.",
    character: "Floral, cozy, and softly spiced.",
    recipeTitle: "Honey cinnamon latte",
    ingredients: [{ amount: "36 ml", item: "Double espresso" }, { amount: "15 g", item: "Honey" }, { amount: "140 ml", item: "Steamed milk" }, { amount: "1 pinch", item: "Ground cinnamon" }],
    steps: ["Stir honey and cinnamon into the fresh espresso.", "Steam milk until silky and glossy.", "Pour the milk into the espresso and dust lightly with cinnamon."],
    visual: "milk",
    tone: "#c88d4f",
  },
  {
    slug: "galao",
    name: "Galão",
    type: "Milk coffee",
    origin: "Portugal",
    served: "Hot",
    withMilk: true,
    strength: 2,
    sweetness: 2,
    description: "A tall Portuguese coffee with one part espresso and three parts foamed milk.",
    character: "Gentle, tall, and breakfast-friendly.",
    recipeTitle: "Portuguese galão",
    ingredients: [{ amount: "40 ml", item: "Double espresso" }, { amount: "120 ml", item: "Steamed milk" }],
    steps: ["Pull the espresso into a tall heatproof glass.", "Steam three times that volume of milk to a light, glossy foam.", "Pour the milk over the espresso and serve hot."],
    visual: "milk",
    tone: "#c3a382",
  },
  {
    slug: "kopi-susu",
    name: "Kopi Susu",
    type: "Milk coffee",
    origin: "Indonesia",
    served: "Hot",
    withMilk: true,
    strength: 4,
    sweetness: 5,
    description: "Indonesian coffee served with milk; this rich variation uses sweetened condensed milk.",
    character: "Roasty, sweet, and comforting.",
    recipeTitle: "Condensed-milk kopi susu",
    ingredients: [{ amount: "20 g", item: "Medium-fine robusta coffee" }, { amount: "150 ml", item: "Hot water" }, { amount: "25 ml", item: "Sweetened condensed milk" }],
    steps: ["Add condensed milk to a heatproof glass.", "Brew the coffee strong and strain out the grounds.", "Pour over the condensed milk and stir to taste."],
    visual: "milk",
    tone: "#9f6842",
  },
  {
    slug: "kopi-tubruk",
    name: "Kopi Tubruk",
    type: "Black coffee",
    origin: "Indonesia",
    served: "Hot",
    withMilk: false,
    strength: 4,
    sweetness: 2,
    description: "Fine coffee steeped directly in the cup, leaving a deep layer of grounds below.",
    character: "Earthy, direct, and traditional.",
    recipeTitle: "Traditional kopi tubruk",
    ingredients: [{ amount: "12 g", item: "Finely ground coffee" }, { amount: "200 ml", item: "Just-boiled water" }, { amount: "Optional", item: "Sugar" }],
    steps: ["Add the coffee and optional sugar directly to a sturdy glass.", "Pour over the hot water and stir once.", "Rest for 4 minutes so the grounds settle, then sip carefully."],
    visual: "black",
    tone: "#574238",
  },
  {
    slug: "dirty-chai",
    name: "Dirty Chai",
    type: "Milk coffee",
    origin: "Modern café culture",
    served: "Hot",
    withMilk: true,
    strength: 3,
    sweetness: 3,
    description: "Spiced chai and steamed milk sharpened with a fresh shot of espresso.",
    character: "Fragrant, warming, and energetic.",
    recipeTitle: "Spiced dirty chai",
    ingredients: [{ amount: "30 ml", item: "Espresso" }, { amount: "100 ml", item: "Strong chai concentrate" }, { amount: "100 ml", item: "Steamed milk" }],
    steps: ["Warm the chai concentrate and pour it into a large cup.", "Add a fresh espresso shot.", "Top with steamed milk and a light cap of foam."],
    visual: "milk",
    tone: "#a75e3d",
  },
];

export const coffees = z.array(coffeeSchema).parse(coffeeData);

export const coffeeBrowserItems: CoffeeBrowserItem[] = coffees.map((coffee) => ({
  description: coffee.description,
  name: coffee.name,
  origin: coffee.origin,
  served: coffee.served,
  slug: coffee.slug,
  tone: coffee.tone,
  type: coffee.type,
  visual: coffee.visual,
  withMilk: coffee.withMilk,
}));

export const coffeeDiscoveryItems: CoffeeDiscoveryItem[] = coffees.map((coffee) => ({
  character: coffee.character,
  name: coffee.name,
  origin: coffee.origin,
  served: coffee.served,
  slug: coffee.slug,
  strength: coffee.strength,
  sweetness: coffee.sweetness,
  type: coffee.type,
  withMilk: coffee.withMilk,
}));

export function getCoffee(slug: string) {
  return coffees.find((coffee) => coffee.slug === slug);
}

export const getRelatedCoffees = (coffee: Coffee, limit = 3) => coffees
  .filter((candidate) => candidate.slug !== coffee.slug)
  .map((candidate) => ({
    coffee: candidate,
    score:
      Number(candidate.type === coffee.type) * 3
      + Number(candidate.served === coffee.served) * 2
      + Number(candidate.withMilk === coffee.withMilk),
  }))
  .sort((left, right) => right.score - left.score)
  .slice(0, limit)
  .map(({ coffee: relatedCoffee }) => relatedCoffee);
